name: travel_guide
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^0.19.0
    http: ^0.12.2
    provider: ^4.3.2+2
    cupertino_icons: ^0.1.3
    shared_preferences: 0.5.12+4
    loading_animations: ^2.1.0
    cloud_firestore: ^0.13.5
    firebase_auth: ^0.16.1
    sqflite: ^1.1.5
    path: ^1.6.2
    location: ^2.3.5
    google_maps_flutter: ^0.5.17
    flushbar: ^1.10.4
    flutter_polyline_points: ^0.2.4
    flutter_config: ^1.0.8

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/images/location.svg
        - assets/images/signup.svg
        - assets/images/google_icon.png
        - assets/images/icon_male.png
        - assets/images/person.png
        - assets/images/pandal.png
        - .env
    fonts:
        - family: Raleway
          fonts:
              - asset: assets/fonts/Raleway-Regular.ttf
              - asset: assets/fonts/Raleway-Bold.ttf
                weight: 700
              - asset: assets/fonts/Raleway-Black.ttf
                weight: 900
        - family: Pass_key
          fonts:
              - asset: assets/icons/Pass_key.ttf
