/// Flutter icons Pass_key
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pass_key
///      fonts:
///       - asset: fonts/Pass_key.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Pass_key {
  Pass_key._();

  static const _kFontFam = 'Pass_key';
  static const _kFontPkg = null;

  static const IconData key =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
